export const TOGGLE_SLAVE_MODE = "TOGGLE_SLAVE_MODE";
export type TOGGLE_SLAVE_MODE = typeof TOGGLE_SLAVE_MODE;

export const SET_EVENT_CONFIG = "SET_EVENT_CONFIG";
export type SET_EVENT_CONFIG = typeof SET_EVENT_CONFIG;

export const SET_EVENT = "SET_EVENT";
export type SET_EVENT = typeof SET_EVENT;

export const SET_NETWORK_HOST = "SET_NETWORK_HOST";
export type SET_NETWORK_HOST = typeof SET_NETWORK_HOST;

export const SET_PRACTICE_SCHEDULE = "SET_PRACTICE_SCHEDULE";
export type SET_PRACTICE_SCHEDULE = typeof SET_PRACTICE_SCHEDULE;

export const SET_QUALIFICATION_SCHEDULE = "SET_QUALIFICATION_SCHEDULE";
export type SET_QUALIFICATION_SCHEDULE = typeof SET_QUALIFICATION_SCHEDULE;

export const SET_FINALS_SCHEDULE = "SET_FINALS_SCHEDULE";
export type SET_FINALS_SCHEDULE = typeof SET_FINALS_SCHEDULE;

export const SET_ELIMINATIONS_SCHEDULE = "SET_ELIMINATIONS_SCHEDULE";
export type SET_ELIMINATIONS_SCHEDULE = typeof SET_ELIMINATIONS_SCHEDULE;

export const SET_MATCH_CONFIG = "SET_MATCH_CONFIG";
export type SET_MATCH_CONFIG = typeof SET_MATCH_CONFIG;

export const SET_MASTER_HOST = "SET_MASTER_HOST";
export type SET_MASTER_HOST = typeof SET_MASTER_HOST;

export const SET_SLAVE_ID = "SET_SLAVE_ID";
export type SET_SLAVE_ID = typeof SET_SLAVE_ID;

export const SET_TOA_CONFIG = "SET_TOA_CONFIG";
export type SET_TOA_CONFIG = typeof SET_TOA_CONFIG;

export const SET_BACKUP_DIR = "SET_BACKUP_DIR";
export type SET_BACKUP_DIR = typeof SET_BACKUP_DIR;