export const UPDATE_PROCESS_LIST = "UPDATE_PROCESS_LIST";
export type UPDATE_PROCESS_LIST = typeof UPDATE_PROCESS_LIST;

export const DISABLE_NAVIGATION = "DISABLE_NAVIGATION";
export type DISABLE_NAVIGATION = typeof DISABLE_NAVIGATION;

export const INCREMENT_COMPLETED_STEP = "INCREMENT_COMPLETED_STEP";
export type INCREMENT_COMPLETED_STEP = typeof INCREMENT_COMPLETED_STEP;