export const CHANGE_ACTIVE_VIEW = "CHANGE_ACTIVE_VIEW";
export type CHANGE_ACTIVE_VIEW = typeof CHANGE_ACTIVE_VIEW;

export const DISABLE_NAVIGATION = "DISABLE_NAVIGATION";
export type DISABLE_NAVIGATION = typeof DISABLE_NAVIGATION;

export const INCREMENT_COMPLETED_STEP = "INCREMENT_COMPLETED_STEP";
export type INCREMENT_COMPLETED_STEP = typeof INCREMENT_COMPLETED_STEP;