DROP TABLE IF EXISTS "event";
DROP TABLE IF EXISTS "team";
DROP TABLE IF EXISTS "alliance";
DROP TABLE IF EXISTS "ranking";
DROP TABLE IF EXISTS "schedule";
DROP TABLE IF EXISTS "match";
DROP TABLE IF EXISTS "match_participant";
DROP TABLE IF EXISTS "match_detail";