ALTER TABLE "ranking" ADD ranking_score INT;
ALTER TABLE "ranking" ADD auto_points INT;
ALTER TABLE "ranking" ADD end_points INT;
ALTER TABLE "ranking" ADD tele_points INT;

ALTER TABLE "match_detail" red_auto_bottom_cells INT;
ALTER TABLE "match_detail" red_auto_outer_cells INT;
ALTER TABLE "match_detail" red_auto_inner_cells INT;
ALTER TABLE "match_detail" red_auto_robot_one_crossed INT;
ALTER TABLE "match_detail" red_auto_robot_two_crossed INT;
ALTER TABLE "match_detail" red_auto_robot_three_crossed INT;
ALTER TABLE "match_detail" red_tele_bottom_cells INT;
ALTER TABLE "match_detail" red_tele_outer_cells INT;
ALTER TABLE "match_detail" red_tele_inner_cells INT;
ALTER TABLE "match_detail" red_end_robot_one_status INT;
ALTER TABLE "match_detail" red_end_robot_two_status INT;
ALTER TABLE "match_detail" red_end_robot_three_status INT;
ALTER TABLE "match_detail" red_end_equalized INT;
ALTER TABLE "match_detail" red_stage_one_cells INT;
ALTER TABLE "match_detail" red_stage_two_cells INT;
ALTER TABLE "match_detail" red_stage_three_cells INT;
ALTER TABLE "match_detail" red_rotation_control INT;
ALTER TABLE "match_detail" red_position_control INT;
ALTER TABLE "match_detail" red_stage INT;

ALTER TABLE "match_detail" blue_auto_bottom_cells INT;
ALTER TABLE "match_detail" blue_auto_outer_cells INT;
ALTER TABLE "match_detail" blue_auto_inner_cells INT;
ALTER TABLE "match_detail" blue_auto_robot_one_crossed INT;
ALTER TABLE "match_detail" blue_auto_robot_two_crossed INT;
ALTER TABLE "match_detail" blue_auto_robot_three_crossed INT;
ALTER TABLE "match_detail" blue_tele_bottom_cells INT;
ALTER TABLE "match_detail" blue_tele_outer_cells INT;
ALTER TABLE "match_detail" blue_tele_inner_cells INT;
ALTER TABLE "match_detail" blue_end_robot_one_status INT;
ALTER TABLE "match_detail" blue_end_robot_two_status INT;
ALTER TABLE "match_detail" blue_end_robot_three_status INT;
ALTER TABLE "match_detail" blue_end_equalized INT;
ALTER TABLE "match_detail" blue_stage_one_cells INT;
ALTER TABLE "match_detail" blue_stage_two_cells INT;
ALTER TABLE "match_detail" blue_stage_three_cells INT;
ALTER TABLE "match_detail" blue_rotation_control INT;
ALTER TABLE "match_detail" blue_position_control INT;
ALTER TABLE "match_detail" blue_stage INT;