export const SET_ACTIVE_MATCH = "SET_ACTIVE_MATCH";
export type SET_ACTIVE_MATCH = typeof SET_ACTIVE_MATCH;

export const SET_MATCH_STATE = "SET_MATCH_STATE";
export type SET_MATCH_STATE = typeof SET_MATCH_STATE;

export const SET_MATCH_DURATION = "SET_MATCH_DURATION";
export type SET_MATCH_DURATION = typeof SET_MATCH_DURATION;

export const UPDATE_SCORING_OBJECT = "SET_SCORING_OBJECT";
export type UPDATE_SCORING_OBJECT = typeof UPDATE_SCORING_OBJECT;