export const SET_ACTIVE_MATCH = "SET_ACTIVE_MATCH";
export type SET_ACTIVE_MATCH = typeof SET_ACTIVE_MATCH;

export const SET_ACTIVE_PARTICIPANTS = "SET_ACTIVE_PARTICIPANTS";
export type SET_ACTIVE_PARTICIPANTS = typeof SET_ACTIVE_PARTICIPANTS;

export const SET_ACTIVE_DETAILS = "SET_ACTIVE_DETAILS";
export type SET_ACTIVE_DETAILS = typeof SET_ACTIVE_DETAILS;

export const SET_MATCH_STATE = "SET_MATCH_STATE";
export type SET_MATCH_STATE = typeof SET_MATCH_STATE;

export const SET_MATCH_DURATION = "SET_MATCH_DURATION";
export type SET_MATCH_DURATION = typeof SET_MATCH_DURATION;

export const UPDATE_PARTICIPANT_STATUS = "UPDATE_PARTICIPANT_STATUS";
export type UPDATE_PARTICIPANT_STATUS = typeof UPDATE_PARTICIPANT_STATUS;